### PR TITLE
pull master into local srid/testing branch

### PR DESCRIPTION
**Pull request by Geometer1729**

### CODE REVIEW

**Review by nixinator — CHANGES_REQUESTED** [review]
So you have forked sydtest to your own repo? why?

**Comment by MatthewCroughan** [comment]
@nixinator Looks like it's just for testing. The amount of PRs we're being tagged in due to this workflow is annoying though, perhaps we can only be notified of changes that are being merged into Master somehow.

**Comment by nixinator** [comment]
> @nixinator Looks like it's just for testing. The amount of PRs we're being tagged in due to this workflow is annoying though, perhaps we can only be notified of changes that are being merged into Master somehow.

That would help somewhat, my mutonomican notifications are looking like close encounters of the 5th kind.

**Comment by Geometer1729** [comment]
> So you have forked sydtest to your own repo? why?

Srid has a fork that supports ghc921 and the original has a branch that supports hedgehog, I need one that supports both. Once it works I'll look into upstreaming it to Srid's fork.

**Comment by Geometer1729** [comment]
> @nixinator Looks like it's just for testing. The amount of PRs we're being tagged in due to this workflow is annoying though, perhaps we can only be notified of changes that are being merged into Master somehow.

This repo is just a fork of plutarch for a PR, so you'll be taged when the pr is taken out of draft mode anyway.

**Comment by nixinator** [comment]
OK! thanks for the heads up!

**Pull request closed without merging**
